from __future__ import annotations
"""
Unified LLM Client — Gemini primary, Groq secondary fallback.
Both are read fresh from env on each call (no lru_cache) so .env changes
are picked up without restart.

Priority:
  1. Google Gemini (google-genai SDK)
  2. Groq (llama-3.1-8b-instant or configured model)
  3. Deterministic fallback (no AI — text generated by Python logic)
"""
import logging
import os
from typing import Any

logger = logging.getLogger(__name__)

# ── SDK imports — graceful degradation ───────────────────────────────────────
try:
    from google import genai
    from google.genai import types as genai_types
    _GEMINI_SDK = True
except ImportError:
    genai = None          # type: ignore
    genai_types = None    # type: ignore
    _GEMINI_SDK = False
    logger.warning("google-genai SDK not installed")

try:
    from groq import Groq as GroqClient
    _GROQ_SDK = True
except ImportError:
    GroqClient = None     # type: ignore
    _GROQ_SDK = False
    logger.warning("groq SDK not installed")


# ── Key / model helpers ───────────────────────────────────────────────────────

def _gemini_key() -> str:
    from app.config.settings import get_settings
    return get_settings().GEMINI_API_KEY.strip()

def _gemini_model() -> str:
    from app.config.settings import get_settings
    return get_settings().GEMINI_MODEL.strip()

def _groq_key() -> str:
    from app.config.settings import get_settings
    key = get_settings().GROQ_API_KEY.strip()
    if not key:
        # .env uses "Groq_API_KEY" — pydantic case_sensitive=False should catch it,
        # but also check raw env as safety net
        import os
        key = (
            os.environ.get("Groq_API_KEY", "")
            or os.environ.get("GROQ_API_KEY", "")
        ).strip()
    return key

def _groq_model() -> str:
    from app.config.settings import get_settings
    return get_settings().GROQ_MODEL.strip()


# ── Client factories ──────────────────────────────────────────────────────────

def get_client():
    """Return Gemini client or None."""
    if not _GEMINI_SDK:
        return None
    key = _gemini_key()
    if not key:
        return None
    try:
        return genai.Client(api_key=key)
    except Exception as exc:
        logger.error("Gemini client init failed: %s", exc)
        return None


def get_groq_client():
    """Return Groq client or None."""
    if not _GROQ_SDK:
        return None
    key = _groq_key()
    if not key:
        return None
    try:
        return GroqClient(api_key=key)
    except Exception as exc:
        logger.error("Groq client init failed: %s", exc)
        return None


def get_model_name() -> str:
    if _gemini_key():
        return _gemini_model()
    if _groq_key():
        return _groq_model()
    return "none"


def is_available() -> bool:
    return get_client() is not None or get_groq_client() is not None


# ── Core generate functions ───────────────────────────────────────────────────

async def generate_text(
    prompt: str,
    system: str = "",
    temperature: float = 0.3,
    max_output_tokens: int = 1024,
) -> tuple[str, bool]:
    """
    Try Gemini first, then Groq, then return ("", False).
    Returns (text, is_ai_generated).
    """
    # ── 1. Try Gemini ─────────────────────────────────────────────────────────
    gemini = get_client()
    if gemini is not None:
        try:
            contents: list[Any] = []
            if system:
                contents.append(system)
            contents.append(prompt)
            config = genai_types.GenerateContentConfig(
                temperature=temperature,
                max_output_tokens=max_output_tokens,
            )
            resp = gemini.models.generate_content(
                model=_gemini_model(),
                contents=contents,
                config=config,
            )
            # Handle models that return thought_signature parts alongside text
            text = ""
            try:
                text = (resp.text or "").strip()
            except Exception:
                # Fallback: concatenate text parts manually
                for part in getattr(resp, "candidates", [{}])[0].get("content", {}).get("parts", []):
                    if hasattr(part, "text") and part.text:
                        text += part.text
                text = text.strip()
            if text:
                logger.debug("Gemini responded (%d chars)", len(text))
                return text, True
        except Exception as exc:
            logger.warning("Gemini call failed: %s — trying Groq", exc)

    # ── 2. Try Groq ──────────────────────────────────────────────────────────
    groq = get_groq_client()
    if groq is not None:
        try:
            messages = []
            if system:
                messages.append({"role": "system", "content": system})
            messages.append({"role": "user", "content": prompt})

            resp = groq.chat.completions.create(
                model=_groq_model(),
                messages=messages,
                temperature=temperature,
                max_tokens=max_output_tokens,
                timeout=15,
            )
            text = (resp.choices[0].message.content or "").strip()
            if text:
                logger.debug("Groq responded (%d chars)", len(text))
                return text, True
        except Exception as exc:
            logger.warning("Groq call failed: %s", exc)

    return "", False


async def generate_json(
    prompt: str,
    system: str = "",
    temperature: float = 0.2,
) -> tuple[dict, bool]:
    """Generate and parse a JSON response."""
    import json as _json
    text, ok = await generate_text(prompt, system=system, temperature=temperature)
    if not ok or not text:
        return {}, False
    clean = text.strip()
    if clean.startswith("```"):
        clean = clean.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    try:
        return _json.loads(clean), True
    except Exception:
        return {"raw": text}, True


# ── Embeddings ────────────────────────────────────────────────────────────────

def get_embedding(text: str) -> list[float]:
    """Gemini text-embedding-004. Returns [] on failure."""
    c = get_client()
    if c is None:
        return []
    try:
        response = c.models.embed_content(
            model="text-embedding-004",
            contents=text,
        )
        embs = getattr(response, "embeddings", None)
        if embs and len(embs) > 0:
            values = getattr(embs[0], "values", None)
            if values:
                return list(values)
        if hasattr(response, "embedding"):
            return list(response.embedding.values)
        return []
    except Exception as exc:
        logger.warning("Embedding failed: %s", exc)
        return []


def embeddings_available() -> bool:
    return get_client() is not None


# ── Status ────────────────────────────────────────────────────────────────────

def llm_status() -> dict:
    gemini_ok = get_client() is not None
    groq_ok = get_groq_client() is not None
    return {
        "gemini": "connected" if gemini_ok else "unavailable",
        "groq": "connected" if groq_ok else "unavailable",
        "active": "gemini" if gemini_ok else ("groq" if groq_ok else "none"),
        "model": get_model_name(),
        "fallback_mode": not (gemini_ok or groq_ok),
    }
